# サーバーポート設定
server.port=${PORT:8080}

# アプリ名・フォーマット設定
spring.application.name=birthday
spring.mvc.format.date=yyyy-MM-dd

# データベースの自動設定を無効化（重要！）
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration