server.port=8080
spring.application.name=birthday
spring.mvc.format.date=yyyy-MM-dd

# DB接続
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgrestest
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# OpenAI API設定（ここを書き換えました）
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o

# サーバー（Render）が指定するポート番号で起動できるようにする魔法の2行
server.port=${PORT:8080}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration